# Chapter 9

#  Introduction to Numpy

In [11]:
 import numpy as np

### 9.1 Arrays

In [9]:
from random import random
from operator import truediv
l1 = [random() for i in range(1000)]
l2 = [random() for i in range(1000)]
# %timeit s = sum(map(truediv,l1,l2))

In [12]:
a1 = np.array(l1)
a2 = np.array(l2)
# %timeit s = np.sum(a1/a2)

Đoạn code tạo 2 dãy số ngẫu nhiên rồi so sánh tốc độ cộng kết quả chia từng phần tử bằng Python thuần và NumPy.

####  9.1.1 Creation

In [6]:
list = [1,2,4]
table = np.array(list)
print(table)

[1 2 4]


Chuyển list [1, 2, 4] thành mảng NumPy và in ra [1 2 4].

In [7]:
print(type(table))

<class 'numpy.ndarray'>


In ra kiểu dữ liệu của table là numpy.ndarray.

In [15]:
 list_2 = [ [1,2,3], [4,5,6] ]
 table_2 = np.array(list_2)
 print(table_2)

[[1 2 3]
 [4 5 6]]


Tạo mảng NumPy 2 chiều từ list [[1, 2, 3], [4, 5, 6]] và in ra

In [9]:
print(type(table_2))

<class 'numpy.ndarray'>


In ra kiểu dữ liệu của table_2 là numpy.ndarray.

In [11]:
tup = (1, 2, 3)
table = np.array(tup)
print(table)

[1 2 3]


Chuyển tuple (1, 2, 3) thành mảng NumPy và in ra \[1 2 3].

In [12]:
 print(type(table))

<class 'numpy.ndarray'>


In ra kiểu dữ liệu của table là numpy.ndarray.

In [13]:
 table = np.array([3, 2, 5, 1, 6, 5])
 table.shape = (3,2)
 print(table)

[[3 2]
 [5 1]
 [6 5]]


Tạo mảng NumPy từ [3, 2, 5, 1, 6, 5], đổi thành ma trận 3 hàng 2 cột và in ra

In [14]:
 print( np.zeros(4) )

[0. 0. 0. 0.]


Tạo mảng gồm 4 phần tử 0.0 và in ra \[0. 0. 0. 0.].

In [16]:
print( np.zeros(4, dtype = "int") )

[0 0 0 0]


Tạo mảng gồm 4 phần tử 0 kiểu số nguyên và in ra [0 0 0 0].

In [18]:
x = np.zeros(4, dtype = "int")
print(x, x.dtype)

[0 0 0 0] int64


Tạo mảng [0 0 0 0] kiểu số nguyên và in ra [0 0 0 0] int64.

In [19]:
y = x.astype("float")
print(x, x.dtype)

[0 0 0 0] int64


Tạo mảng [0 0 0 0] kiểu số nguyên và in ra [0 0 0 0] int64.

In [20]:
print(y, y.dtype)

[0. 0. 0. 0.] float64


Tạo mảng \[0. 0. 0. 0.] kiểu số thực và in ra \[0. 0. 0. 0.] float64.

Tạo mảng 2 hàng 3 cột toàn số 0.0 và in ra

In [21]:
print( np.zeros((2, 3, 4)) )

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


Tạo mảng 3 chiều kích thước 2×3×4 toàn số 0.0 và in ra các khối giá trị 0.0.

In [31]:
print( np.empty((2, 3), dtype = "int") )

[[9218868437227405312 9218868437227405312 9218868437227405312]
 [9218868437227405312 9218868437227405312 9218868437227405312]]


Tạo mảng 2 hàng 3 cột kiểu số nguyên nhưng giá trị ngẫu nhiên (không khởi tạo) và in ra các số rác có sẵn trong bộ nhớ.

In [24]:
 print( np.ones((2, 3), dtype = "float") )

[[1. 1. 1.]
 [1. 1. 1.]]


Tạo mảng 2 hàng 3 cột toàn số 1.0 và in ra

In [25]:
 print( np.full((2, 3), 10, dtype = "float") )

[[10. 10. 10.]
 [10. 10. 10.]]


Tạo mảng 2 hàng 3 cột toàn số 10.0 và in ra

In [26]:
 print( np.full((2, 3), np.inf) )

[[inf inf inf]
 [inf inf inf]]


Tạo mảng 2 hàng 3 cột toàn giá trị vô cực và in ra

In [32]:
 print( np.eye(2, dtype="int64") )

[[1 0]
 [0 1]]


Tạo ma trận đơn vị 2×2 kiểu số nguyên 64-bit và in ra

In [33]:
 print( np.eye(3, k=-1) )

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


Tạo ma trận đơn vị 3×3 nhưng đường chéo chính được dịch xuống 1 hàng (k = -1) và in ra

In [34]:
print( np.identity(3, dtype = "int") )

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Tạo ma trận đơn vị 3×3 kiểu số nguyên và in ra

In [13]:
np.arange( start, stop, step, dtype )

NameError: name 'start' is not defined

In [3]:
print( np.arange(5) )

[0 1 2 3 4]


In [4]:
print( np.arange(2, 5) )

[2 3 4]


In [5]:
print( np.arange(2, 10, 2) )

[2 4 6 8]


np.arange() tạo mảng số cách đều theo giá trị start, stop, step.

####  9.1.2 Dimensions

In [10]:
 print("ndim tableau : ", table.ndim)

ndim tableau :  2


In [11]:
print("ndim table_2 : ", table_2.ndim)

ndim table_2 :  2


In [12]:
 print("size table : ", table.size)

size table :  6


In [13]:
print("size table_2: ", table_2.size)

size table_2:  12


In [18]:
print("np.size(table):", np.size(table))

np.size(table): 6


In [15]:
print("size table: ", table.shape)

size table:  (2, 3)


In [19]:
 print("size table_2: ", table_2.shape)

size table_2:  (2, 3)


In ra số chiều của mảng table.

####  9.1.3 Extracting Elements from an Array

In [7]:
table_1 = np.arange(1,13)
table_2 = [ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
table_2 = np.array(table_2)

In [10]:
 message = "table_{}[0] : {} (type : {})"
 print(message.format(0, table_1[0], type(table_1[0])))

table_0[0] : 1 (type : <class 'numpy.int64'>)


In một dòng: Hiển thị giá trị đầu tiên của table\_1 cùng chỉ số và kiểu dữ liệu của nó.

In [24]:
 print(message.format(1, table_2[0], type(table_2[0])))

table_1[0] : [1 2 3] (type : <class 'numpy.ndarray'>)


Hiển thị giá trị đầu tiên của table\_2, kèm chỉ số 1 và kiểu dữ liệu của giá trị đó.


In [25]:
print("table_1[-1] : ", table_1[-1]) # last element

table_1[-1] :  12


Hiển thị phần tử cuối cùng của table\_1.


In [26]:
 print("table_2[-1] : ", table_2[-1]) # last element

table_2[-1] :  [10 11 12]


Hiển thị phần tử cuối cùng của table\_2.

In [28]:
# the elements from the 2nd (not included) to the 4th
print("Slice Table 1 : \n", table_1[2:4])


Slice Table 1 : 
 [3 4]


Hiển thị các phần tử từ vị trí thứ 3 đến thứ 4 của table\_1.


In [29]:
print("Sclie Table 2 : \n", table_2[2:4])

Sclie Table 2 : 
 [[ 7  8  9]
 [10 11 12]]


Hiển thị các phần tử từ vị trí thứ 3 đến thứ 4 của table\_2.


In [30]:
 # Within the 3rd element, access the 1st element
 print(table_2[2][0])

7


Truy cập phần tử đầu tiên bên trong phần tử thứ 3 của table\_2.

In [31]:
 print(table_2[2,0])

7


Tiếp tục thao tác với phần tử, cắt lát, kiểm tra kiểu hoặc lặp qua danh sách/mảng.

In [33]:
print("Second column: \n", table_2[:, [1]])

Second column: 
 [[ 2]
 [ 5]
 [ 8]
 [11]]


Lấy cột thứ hai của table\_2 (mọi hàng, chỉ cột 1) nếu table\_2 là numpy array.


In [34]:
 print("Second and third columns: \n", table_2[:, [1,2]])

Second and third columns: 
 [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


Lấy cột thứ hai và thứ ba của table\_2 (mọi hàng, chỉ cột 1 và 2) nếu table\_2 là numpy array.

In [35]:
 print("2nd and 4th elements: \n", table_2[[1,3]])

2nd and 4th elements: 
 [[ 4  5  6]
 [10 11 12]]


Lấy phần tử thứ 2 và thứ 4 của table\_2 nếu table\_2 là numpy array.

#####  9.1.3.1 Extraction Using Boolean

In [36]:
 table = np.array([0, 3, 2, 5, 1, 4])
 res = table[[True, False, True, False, True, True]]
 print(res)

[0 2 1 4]


Chọn các phần tử của table tương ứng với True trong mảng boolean.

In [37]:
 mask = table % 2 == 0
 print(mask)

[ True False  True False False  True]


Tạo mảng boolean đánh dấu các phần tử chẵn trong table.


In [38]:
 print(type(mask))

<class 'numpy.ndarray'>


Hiển thị kiểu dữ liệu của mask, là numpy ndarray.


In [39]:
print(table[mask])

[0 2 4]


Chọn các phần tử chẵn trong table dựa trên mask.


#### 9.1.4 Modification

In [40]:
table = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
table[0] = [11, 22, 33]
print(table)

[[11 22 33]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Thay hàng đầu tiên bằng \[11, 22, 33] và in mảng.


In [42]:
table[0] = 100
print(table)

[[100 100 100]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]


Đặt toàn bộ hàng đầu tiên thành 100 và in mảng.


In [43]:
table[0:2] = 100
print(table)

[[100 100 100]
 [100 100 100]
 [  7   8   9]
 [ 10  11  12]]


Đặt toàn bộ hai hàng đầu tiên thành 100 và in mảng.


In [44]:
table[:] = 0
print(table)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


Đặt tất cả phần tử của table thành 0 và in mảng.


####  9.1.4.1 Insterting Elements

In [45]:
t_1 = np.array([1,3,5])
print("t_1 : ", t_1)

t_1 :  [1 3 5]


Tạo mảng t\_1 với các phần tử \[1, 3, 5] và in ra.


In [17]:
 t_2 = np.array([[1,2,3], [5,6,7]])
 print("t_2 : \n", t_2)

t_2 : 
 [[1 2 3]
 [5 6 7]]


In [13]:
t_1 = np.append(t_1, 1)
print("t_1 after the insertion: ", t_1)

t_1 after the insertion:  [1 3 5 1]


Thêm 1 vào cuối t\_1 và in mảng mới.


In [14]:
 t_2 = np.array([[1,2,3], [5,6,7]])
 print("t_2 : \n", t_2)

t_2 : 
 [[1 2 3]
 [5 6 7]]


Tạo mảng 2 chiều t\_2 và in ra.


In [18]:
add_col_t_2 = np.array([[4], [8]])
t_2 = np.append(t_2,add_col_t_2, axis = 1)
print("t_2 after the insertion: \n", t_2)

t_2 after the insertion: 
 [[1 2 3 4]
 [5 6 7 8]]


Thêm cột \[4, 8] vào t\_2 và in ra.

In [18]:
ajout_ligne_t_2 = np.array([10, 11, 12, 13])
t_2 = np.vstack([t_2,ajout_ligne_t_2])
print("t_2 après ajout ligne : \n", t_2)

t_2 après ajout ligne : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


Thêm hàng \[10, 11, 12, 13] vào t\_2 và in mảng mới.

#####  9.1.4.2 Deleting / Removing Elements

In [19]:
 print("t_1 : ", t_1)
 # Remove the last element

t_1 :  [1 3 5 1]


Hiển thị t\_1 trước khi xóa phần tử cuối.


In [20]:
np.delete(t_1, (-1))

array([1, 3, 5])

Xóa phần tử cuối của t\_1 và trả về mảng mới.


In [21]:
print("t_1 : ", t_1)
 # Remove the first and second elements:

t_1 :  [1 3 5 1]


Hiển thị t\_1 trước khi xóa phần tử đầu và thứ hai.

In [22]:
 t_1 = np.delete(t_1, ([0, 2]))
 print(t_1)

[3 1]


Xóa phần tử đầu tiên và phần tử thứ ba (chỉ số 0 và 2) của t\_1 và in mảng mới.


In [23]:
print("t_2 : ", t_2)
 # Remove the last column:

t_2 :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


Hiển thị t\_2 trước khi xóa cột cuối.


In [25]:
np.delete(t_2, (0), axis=1)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [11, 12, 13]])

Xóa cột đầu tiên của t\_2 (axis=1) và trả về mảng mới.


Delete multiple columns:

In [26]:
print("t_2 : ", t_2)
 # Remove the first and third columns:

t_2 :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


Hiển thị t\_2 trước khi xóa cột thứ nhất và thứ ba.


In [27]:
np.delete(t_2, ([0,2]), axis=1)

array([[ 2,  4],
       [ 6,  8],
       [11, 13]])

Xóa cột thứ nhất và thứ ba của t\_2 (axis=1) và trả về mảng mới.


In [28]:
print("t_2 : ", t_2)
 # Remove the first line:

t_2 :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


Hiển thị t\_2 trước khi xóa hàng đầu tiên.

In [29]:
np.delete(t_2, (0), axis=0)

array([[ 5,  6,  7,  8],
       [10, 11, 12, 13]])

Xóa hàng đầu tiên của t\_2 (axis=0) và trả về mảng mới.


In [30]:
print("t_2 : ", t_2)
 # Remove the first and third lines:

t_2 :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


Hiển thị t\_2 trước khi xóa hàng thứ nhất và thứ ba.


In [31]:
np.delete(t_2, ([0,2]), axis=0)

array([[5, 6, 7, 8]])

Xóa hàng thứ nhất và thứ ba của t\_2 (axis=0) và trả về mảng mới.

#### 9.1.5 Copyi of an Array

In [32]:
 table_1 = np.array([1, 2, 3])
 table_2 = table_1


In [33]:
 table_2[0] = 0
 print("Table 1: \n", table_1)

Table 1: 
 [0 2 3]


Đặt hàng đầu tiên của table\_2 bằng 0 nhưng in table\_1, không liên quan.


In [34]:
print("Table 2: \n", table_2)

Table 2: 
 [0 2 3]


Hiển thị table\_2 sau khi thay đổi hàng đầu tiên thành 0.


In [37]:
table_1 = np.array([1, 2, 3])
table_2 = np.array(table_1)
table_2[0] = 0
print("table_1 : ", table_1)

table_1 :  [1 2 3]


table\_1 không thay đổi, vẫn là \[1, 2, 3], vì table\_2 được sao chép riêng.


In [38]:
 print("table_2 : ", table_2)

table_2 :  [0 2 3]


Hiển thị table\_2, hàng đầu tiên đã bị thay đổi thành 0.


In [40]:
table_1 = np.array([1, 2, 3])
table_2 = table_1.copy()
table_2[0] = 0
print("table_1 : ", table_1)

table_1 :  [1 2 3]


table\_1 vẫn giữ nguyên \[1, 2, 3] vì table\_2 là bản sao riêng bằng copy().


In [41]:
 print("table_2 : ", table_2)

table_2 :  [0 2 3]


Hiển thị table\_2, phần tử đầu tiên đã đổi thành 0.

In [42]:
 table_1 = np.array([1, 2, 3, 4])
 table_2 = table_1[:2]
 table_2[0] = 0
 print("table_1 : ", table_1)

table_1 :  [0 2 3 4]


Phần tử đầu tiên của table\_1 cũng bị thay đổi thành 0 vì table\_2 là slice tham chiếu tới table\_1.


In [43]:
print("table_2 : ", table_2)

table_2 :  [0 2]


Hiển thị table\_2, phần tử đầu tiên đã đổi thành 0.


####  9.1.6 Sorting

In [44]:
 table = np.array([3, 2, 5, 1, 6, 5])
 print("Sorted Table: ", np.sort(table))

Sorted Table:  [1 2 3 5 5 6]


Sắp xếp các phần tử của table theo thứ tự tăng dần và in kết quả.


In [45]:
 print("Table: ", table)

Table:  [3 2 5 1 6 5]


Hiển thị table gốc, vẫn giữ nguyên thứ tự ban đầu.

In [19]:
 table = np.array([3, 2, 5, 1, 6, 5])
 table.sort()
 print("The array was modified: ", table)

The array was modified:  [1 2 3 5 5 6]


Sắp xếp table tại chỗ, thay đổi mảng gốc và in kết quả.


####  9.1.7 Transposition

In [20]:
 table = np.array([3, 2, 5, 1, 6, 5])
 table.shape = (3,2)
 print("Array: \n", table)

Array: 
 [[3 2]
 [5 1]
 [6 5]]


Chuyển table thành mảng 3 hàng 2 cột và in ra.

In [48]:
 print("Transposed Array: \n", table.T)

Transposed Array: 
 [[3 5 6]
 [2 1 5]]


In mảng table sau khi chuyển vị (hàng thành cột và cột thành hàng).

In [49]:
print(np.transpose(table))

[[3 5 6]
 [2 1 5]]


In mảng table sau khi chuyển vị, tương đương table.T.

In [52]:
table_transpose = np.transpose(table)
table_transpose[0,0] = 99
print("Array: \n", table)

Array: 
 [[99  2]
 [ 5  1]
 [ 6  5]]


Mảng gốc table cũng thay đổi phần tử \[0,0] thành 99 vì transpose trả về view, không phải bản sao.


In [53]:
print("Transpose of the Array: \n", table_transpose)

Transpose of the Array: 
 [[99  5  6]
 [ 2  1  5]]


Hiển thị mảng đã chuyển vị table\_transpose, phần tử \[0,0] là 99.


In [54]:
print("table: ", table.base)

table:  None


Hiển thị mảng gốc mà table đang tham chiếu; nếu None tức table không phải là view của mảng khác.


In [55]:
 print("table_transpose : ", table_transpose.base)

table_transpose :  [[99  2]
 [ 5  1]
 [ 6  5]]


Hiển thị mảng gốc mà table\_transpose đang tham chiếu; kết quả là table vì transpose trả về view.


#### 9.1.8 Operations on Arrays

##### 9.1.8.1 + and- Operators

In [21]:
t_1 = np.array([1, 2, 3, 4])
t_2 = np.array([5, 6, 7, 8])
t_3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
t_4 = np.array([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])
t_1 + t_2

array([ 6,  8, 10, 12])

Cộng từng phần tử tương ứng của t\_1 và t\_2, kết quả là \[6, 8, 10, 12].


In [57]:
 t_3 + t_4

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

Cộng từng phần tử tương ứng của t_3 và t_4, in kết quả 

In [58]:
t_1- t_2

array([-4, -4, -4, -4])

Trừ từng phần tử của t\_2 khỏi t\_1, kết quả là \[-4, -4, -4, -4].

In [59]:
 print("t_1 + 3 : \n", t_1 + 3)

t_1 + 3 : 
 [4 5 6 7]


Cộng 3 vào từng phần tử của t\_1 và in kết quả.


In [60]:
print("t_1 + 3. : \n", t_1 + 3.)

t_1 + 3. : 
 [4. 5. 6. 7.]


Cộng 3.0 (float) vào từng phần tử của t\_1, kết quả là mảng float.


In [61]:
 print("t_3 + 3 : \n", t_3 + 3)

t_3 + 3 : 
 [[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Cộng 3 vào từng phần tử của t\_3 và in mảng kết quả.


In [62]:
 print("t_3- 3 : \n", t_3- 3)

t_3- 3 : 
 [[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]


Trừ 3 từ từng phần tử của t\_3 và in mảng kết quả.


#####  9.1.8.2 * and / Operators

In [63]:
t_1 * t_2

array([ 5, 12, 21, 32])

Nhân từng phần tử tương ứng của t\_1 và t\_2, kết quả là \[5, 12, 21, 32].


In [64]:
 t_3 * t_4

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

Nhân từng phần tử tương ứng của t_3 và t_4, in kết quả

In [65]:
 t_3 / t_4

array([[0.07692308, 0.14285714, 0.2       , 0.25      ],
       [0.29411765, 0.33333333, 0.36842105, 0.4       ],
       [0.42857143, 0.45454545, 0.47826087, 0.5       ]])

Chia từng phần tử tương ứng của t_3 cho t_4, in kết quả

In [67]:
 print("t_1 * 3 : \n", t_1 * 3)

t_1 * 3 : 
 [ 3  6  9 12]


Nhân từng phần tử của t\_1 với 3 và in kết quả.

In [68]:
print("t_1 / 3 : \n", t_1 / 3)

t_1 / 3 : 
 [0.33333333 0.66666667 1.         1.33333333]


Chia từng phần tử của t\_1 cho 3 và in kết quả.


 ##### 9.1.8.3 Power

In [69]:
print("t_1 ** 3 : \n", t_1 ** 3)

t_1 ** 3 : 
 [ 1  8 27 64]


Lũy thừa từng phần tử của t\_1 lên mũ 3 và in kết quả.


##### 9.1.8.4 Operations on Matrices

In [70]:
 np.dot(t_3, t_4.T)

array([[150, 190, 230],
       [382, 486, 590],
       [614, 782, 950]])

Thực hiện nhân ma trận giữa t\_3 và chuyển vị của t\_4, kết quả là ma trận 3x3 với tích vô hướng của các hàng và cột tương ứng.


In [27]:
np.dot(t_3, t_4)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [28]:
t_3 @ t_4.T

array([[150, 190, 230],
       [382, 486, 590],
       [614, 782, 950]])

Thực hiện nhân ma trận giữa t\_3 và chuyển vị của t\_4 bằng toán tử @, kết quả là ma trận 3x3.


In [29]:
np.dot(t_1, t_3.T)

array([ 30,  70, 110])

Nhân t\_1 (1x4) với t\_3.T (4x3), kết quả là mảng 1x3 chứa các tích vô hướng với từng hàng của t\_3.


####  9.1.9 Logical Operators

In [32]:
t = np.array([[1, 10, 3, 24], [9, 12, 40, 2], [0, 7, 2, 14]])
mask = np.logical_and(t <= 20, t >= 10)
print("mask: \n", mask)

mask: 
 [[False  True False False]
 [False  True False False]
 [False False False  True]]


Tạo mảng boolean mask đánh dấu các phần tử của t nằm trong khoảng từ 10 đến 20.


In [33]:
 print("the elements of t between 10 and 20: \n",
 t[mask])

the elements of t between 10 and 20: 
 [10 12 14]


Chọn và in các phần tử của t nằm trong khoảng từ 10 đến 20.


####  9.1.10 Some Constants

In [34]:
 print("Addition : ", np.nan + 1)

Addition :  nan


Kết quả là nan vì bất cứ phép tính nào với np.nan đều ra nan.


In [35]:
 print("Substraction : ", np.nan- 1)

Substraction :  nan


Kết quả là nan vì bất kỳ phép tính nào với np.nan đều không xác định.


In [36]:
 print("Multiplication : ", np.nan + 1)

Multiplication :  nan


Kết quả là nan vì mọi phép tính với np.nan đều không xác định.


In [37]:
 print("Division : ", np.nan / 1)

Division :  nan


Kết quả là nan vì bất kỳ phép tính nào với np.nan đều không xác định.


#### 9.1.11 Universal functions

In [38]:
 t_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
 t_2 = np.array([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])
 np.log(t_1) # Natural Logarithm

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

Tính logarith tự nhiên (ln) của từng phần tử trong t\_1.


In [39]:
 np.subtract(t_1, t_2) # Substraction of the elements of `t_1` by those of `t_2`

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

np.subtract(t\_1, t\_2) tra ve mot mang moi bang cach tru tung phan tu t\_2 cho tung phan tu t\_1


####  9.1.12 Mathematical and Statistical Methods and Functions

In [40]:
 t_1 = np.array([[1, 2, 3, 4], [-1, 6, 7, 8], [9,-1, 11, 12]])
 print("t_1 : \n", t_1)

t_1 : 
 [[ 1  2  3  4]
 [-1  6  7  8]
 [ 9 -1 11 12]]


t\_1 = np.array(\[\[1, 2, 3, 4], \[-1, 6, 7, 8], \[9, -1, 11, 12]]) in ra mang 2 chieu 3 hang 4 cot


In [41]:
 print("Sum of the elements: ", t_1.sum())

Sum of the elements:  61


print("Sum of the elements: ", t\_1.sum()) in ra tong tat ca phan tu trong mang t\_1


In [42]:
 print("Covariance of the elements: ", t_1.var())

Covariance of the elements:  18.07638888888889


print("Covariance of the elements: ", t\_1.var()) in ra phuong sai cua tat ca phan tu trong mang t\_1


In [44]:
 print("Sum per column: ", t_1.sum(axis=0))

Sum per column:  [ 9  7 21 24]


print("Sum per column: ", t\_1.sum(axis=0)) in ra tong cac phan tu theo tung cot trong mang t\_1


In [45]:
print("Sum per row: ", t_1.sum(axis=1))

Sum per row:  [10 20 31]


print("Sum per row: ", t\_1.sum(axis=1)) in ra tong cac phan tu theo tung hang trong mang t\_1


In [46]:
 t_1 = np.array([[1, 2, 3, 4], [-1, 6, 7, 8], [9,-1, 11, 12]])
 print("t_1 : \n", t_1)

t_1 : 
 [[ 1  2  3  4]
 [-1  6  7  8]
 [ 9 -1 11 12]]


t\_1 = np.array(\[\[1, 2, 3, 4], \[-1, 6, 7, 8], \[9, -1, 11, 12]]) tao mang 2 chieu 3 hang 4 cot va in ra no


In [47]:
print("Variance: ", np.var(t_1))

Variance:  18.07638888888889


print("Variance: ", np.var(t\_1)) in ra phuong sai cua tat ca phan tu trong mang t\_1


In [53]:
 t_1 = np.array([[1, 2, np.nan, 4], [-1, 6, 7, 8], [9,-1, 11, 12]])
 print("Sum: ", np.sum(t_1))

Sum:  nan


Code này tạo mảng t\_1 có giá trị np.nan và khi dùng np.sum(t\_1) se tra ve nan vi bat ky phep tinh tong nao co nan deu ra nan.


In [54]:
print("Sum ignoring NaN values: ", np.nansum(t_1))

Sum ignoring NaN values:  58.0


print("Sum ignoring NaN values: ", np.nansum(t\_1)) in ra tong cac phan tu trong mang t\_1 bo qua gia tri nan


In [55]:
 v_1 = np.array([1, 1, 4, 2])
 w = np.array([1, 1, .5, 1])
 print("Weighted average: ", np.average(v_1, weights=w))

Weighted average:  1.7142857142857142


print("Weightedaverage: ", np.average(v_1, weights=w)) tinh trung binh co trong so cua mang v_1 theo trong so w

### 9.2 Generation of Pseudo-random Numbers

In [56]:
from numpy import random

In [58]:
x = np.random.normal(size=10)
print(x)

[-0.71586133 -0.13090579  0.04743999 -0.69399062 -0.80627821 -0.48372051
  1.48785852  0.15374603 -3.87010636 -0.81932223]


x = np.random.normal(size=10) tao mot mang 10 phan tu ngau nhien tu phan phoi chuan va in ra no


In [59]:
 x = np.random.randn(10, 4)
 print(x)

[[ 9.41946925e-01  8.85578840e-01  6.96388161e-01 -8.51649959e-02]
 [-5.93557079e-01  4.88549896e-01 -9.79942728e-01 -1.92385133e-01]
 [ 7.52452027e-02 -1.02847030e+00  1.32356524e+00 -3.97279416e-01]
 [ 3.72981936e-01  4.84012490e-01 -1.74864731e+00  2.91496451e-01]
 [ 1.98097206e-01 -2.37604430e-01  1.76442247e-01  1.23185500e-01]
 [ 3.83246748e-01 -1.07011972e+00 -2.05703953e+00 -1.89883845e+00]
 [-5.75903401e-01 -2.55233063e-01 -4.51205722e-01 -5.10064430e-02]
 [-2.98977070e-01 -1.13804915e+00 -1.27337578e+00 -1.50223911e+00]
 [ 1.26533729e+00  1.86176673e-01 -2.24079003e+00  1.86382886e-01]
 [ 4.16376682e-01  4.31406250e-01  5.60046304e-04 -4.87036330e-01]]


x = np.random.randn(10, 4) tao mot mang 10 hang 4 cot gom cac so ngau nhien tu phan phoi chuan va in ra no


In [61]:
np.random.seed(1234)
x = np.random.normal(size=10)
print(x)

[ 0.47143516 -1.19097569  1.43270697 -0.3126519  -0.72058873  0.88716294
  0.85958841 -0.6365235   0.01569637 -2.24268495]


np.random.seed(1234) dat seed de tao so ngau nhien co the lap lai
x = np.random.normal(size=10) tao mang 10 phan tu ngau nhien tu phan phoi chuan va in ra no

In [63]:
 from numpy.random import RandomState
 rs = RandomState(123)
 x = rs.normal(10)
 print(x)

8.914369396699438


rs = RandomState(123) tao mot doi tuong RandomState co seed 123
x = rs.normal(10) sinh mot so ngau nhien tu phan phoi chuan (mean=0, std=1) va in ra no

In [64]:
 x = np.arange(10)
 y = np.random.permutation(x)
 print("x : ", x)

x :  [0 1 2 3 4 5 6 7 8 9]


x = np.arange(10) tao mang [0 1 2 3 4 5 6 7 8 9]
y = np.random.permutation(x) tao mot ban tron cua x khong thay doi x ban dau
print("x : ", x) in ra mang x ban dau

In [65]:
 print("y : ", y)

y :  [9 7 4 3 8 2 6 1 0 5]


print("y : ", y) in ra mang y da duoc tron ngau nhien tu x


In [66]:
 x = np.arange(10)
 print("x avant permutation : ", x)

x avant permutation :  [0 1 2 3 4 5 6 7 8 9]


x = np.arange(10) tao mang \[0 1 2 3 4 5 6 7 8 9] va print("x avant permutation : ", x) in ra mang x truoc khi tron ngau nhien


In [67]:
np.random.permutation(x)

array([7, 5, 4, 1, 0, 8, 3, 9, 6, 2])

np.random.permutation(x) tao mot ban tron ngau nhien cua mang x khong thay doi x ban dau


In [68]:
print("xaprès permutation: ",x)

xaprès permutation:  [0 1 2 3 4 5 6 7 8 9]


print("xaprès permutation: ", x) in ra mang x ban dau, van giu nguyen vi np.random.permutation() khong thay doi mang goc


### 9.3 Exercise

###### Firstexercise

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
print("Vector x: ", x)


Vector x:  [1 2 3 4 5]


#####  1. Create this vector using an array called x.

In [5]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])


##### 2. Display the type of x and its length.

In [6]:
   print(type(x))  # <class 'numpy.ndarray'>
   print(len(x))   # 5
   

<class 'numpy.ndarray'>
5


##### 3.Extract the first element, then do the same with the last one.

In [7]:
   first_element = x[0]  # 1
   last_element = x[-1]   # 5
   

##### 4.Extract the first three elements and store them in a vector called a.

In [17]:
x = np.array([1, 2, 3, 4, 5])

##### 5. Extract the 1st, 2nd, and 5th elements of the vector; store them in a vector called b.

In [24]:
b = np.array([10, 20, 30, 40, 50])

##### 6. Add the number 10 to the vector x, then multiply the result by 2.

In [19]:
a = np.array([10, 20, 30, 40, 50])

##### 7. Add a and b, comment on the result.  

In [11]:
 result_ab = a + b

##### 8. Make the following addition: x + a; comment on the result, then look at the result of a + x.

In [20]:
result_x_a = x + a
result_a_x = a + x

##### 9. Multiply the vector by the scalar c which will be set to 2

In [22]:
c = 2
x_scaled = x * c

##### 10. Multiply a and b; comment on the result.

In [25]:
result_a_b = a * b

##### 11. Perform the following multiplication: x * a; comment on the results.

In [26]:
result_x_a_multiplication = x * a

##### 12. Retrieve the positions of the multiples of 2 and store them in a vector called ind, then store only the multiples of 2 of x in a vector called mult_2.

In [27]:
ind = np.where(x % 2 == 0)[0]
mult_2 = x[x % 2 == 0]

##### 13. Display the elements of x that are multiples of 3 and multiples of 2.

In [33]:
multiples_3_and_2 = x[(x % 3 == 0) & (x % 2 == 0)]  

##### 14. Display the elements of x that are multiples of 3 or multiples of 2.

In [32]:
multiples_3_or_2 = x[(x % 3 == 0) | (x % 2 == 0)] 

##### 15. Calculate the sum of the elements of x.

In [34]:
sum_x = np.sum(x)

##### 16. Replace the first element of x with 4.

In [35]:
x[0] = 4

##### 17. Replace the first element of x with the value NaN, then calculate the sum of the elements of x.

In [37]:
x[0] = np.nan
sum_x_nan = np.nansum(x)

ValueError: cannot convert float NaN to integer

##### 18. Delete the vector x.

In [38]:
del x

###### Second exercise

##### 1. Create the following matrix:

In [39]:
   import numpy as np
   A = np.array([[-3, 5, 6], [-1, 2, 2], [1, -1, -1]])
   

##### 2. Display the size of A, its number of columns, its number of rows, and its length.

In [40]:
   print(A.shape)          # (3, 3) - size of A
   print(A.shape[0])       # 3 - number of rows
   print(A.shape[1])       # 3 - number of columns
   print(len(A))           # 3 - length (number of rows)
   

(3, 3)
3
3
3


##### 3. Extract the second column from A, then the first row.

In [41]:
   second_column = A[:, 1]  # array([ 5,  2, -1])
   first_row = A[0, :]       # array([-3,  5,  6])
   

##### 4. Extract the element in the third position in the first line.

In [42]:
element = A[0, 2]  # 6

##### 5. Extract the submatrix of dimension 2 × 2 from the lower corner of A.

In [44]:
submatrix = A[1:3, 1:3]  

##### 6. Calculate the sum of the columns and then the rows of A.

In [46]:
   column_sum = np.sum(A, axis=0)  
   row_sum = np.sum(A, axis=1)

##### 7. Display the diagonal of A.

In [48]:
diagonal = np.diag(A)  

##### 8. Add the vector to A and store it in an object called B.

In [50]:
vector = np.array([[1], [2], [3]])  # Column vector
B = np.hstack((A, vector))  # Add vector to the right of A

##### 9. Remove the fourth vector from B.

In [52]:
# Since B has only 4 columns, we can remove the last column (index 3)
B = B[:, :-1]  # Now B has only 3 columns

##### 10. Remove the first and third rows from B.

In [53]:
B = np.delete(B, [0, 2], axis=0)

##### 11. Add scalar 10 to A.

In [55]:
A_plus_10 = A + 10 

##### 12. Add the vector to the right of the matrix A and store the result in A.

In [56]:
A = np.hstack((A, vector))

##### 13. Add the identity matrix to A.

In [59]:
I = np.eye(3)  # Identity matrix of size 3
A = A + I  # Add identity matrix to A

##### 14. Divide all the elements of the matrix A by 2.

In [60]:
A = A / 2

##### 15. Multiply the matrix A by the line vector

In [61]:
line_vector = np.array([[1, 2, 3]])  # Row vector
result_multiplication = A @ line_vector.T  # Matrix multiplication

##### 16. Display the transposition of A.

In [62]:
A_transpose = A.T

##### 17. Perform the product with transposition 